### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by rob-3** [KnightHacks/DiscordBot-New#4]
I use https://github.com/Microsoft/pyright to lint this project and I get a number of warnings in various files, some of which do actually indicate problems. We should standardize a python linter for dev team projects and then fix the errors everywhere.

**Comment by zenith110** [comment]
Would this linting happen for pr reviews, or after it's merged into the branch?

**Comment by rob-3** [comment]
Either is fine. I'm not actually that well-versed in the python ecosystem and CD/CI so use your discretion. I just like linters in my editor.

**Comment by TorrentofShame** [comment]
Should use https://github.com/python/mypy instead if you want type checking in the linter.

**Comment by rob-3** [comment]
We added flake8 as per #9
